name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Build project
        run: yarn && yarn build

      - name: Upload OOS
        uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: oss-cn-chengdu.aliyuncs.com
          access-key-id: ${{ secrets.SECRET_ID }}
          access-key-secret: ${{ secrets.SECRET_KEY }}
      - name: cp files to aliyun
        run: ossutil cp -rf ./build oss://my-site-jseronline
